webstatistics/appstat/urls.py
from django.urls import path

from . import views

app_name = 'polling'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:poll_id>/', views.questionview, name='questions'),
    path('<int:poll_id>/results/', views.results, name='results'), 
]

webstatistics/webstatistics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polling/', include('appstat.urls'))
]

webstatistics/appstat/models.py
import datetime

from django.db import models
from django.utils import timezone


class Poll(models.Model):
    name = models.CharField(max_length=20)
    date_pub = models.DateTimeField('date published')

    def __str__(self):
        return self.name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_pub <= now

    class Meta:
        verbose_name_plural = 'Polls'


class Question(models.Model):
    poll = models.ForeignKey(Poll, related_name='questions', on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name_plural = 'Questions'


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        
    class Meta:
        verbose_name_plural = 'Choices'

webstatistics/appstat/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone

from .models import Question, Choice, Poll


class IndexView(generic.ListView):
    template_name = 'appstat/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last ten published polls (not including future)."""
        return Poll.objects.filter(date_pub__lte=timezone.now()).order_by('date_pub')[:10]


def questionview(request, poll_id):
    poll_questions = Question.objects.filter(poll_id=poll_id) 
    polling_name = Poll.objects.get(pk=poll_id)
    context = {
        'poll_questions': poll_questions,
        'polling_name': polling_name,
    }
    return render(request, 'appstat/questions.html', context)
   
    
def results(request, poll_id):
    poll_questions = Question.objects.filter(poll_id=poll_id)
    polling_name = Poll.objects.get(pk=poll_id)
    try:
        selected_choice_list = []
        for question in poll_questions:  
            selected_choice = question.choices.get(pk=request.POST[question.question_text]) 
            selected_choice.votes +=1
            selected_choice.save()
            selected_choice_list.append(selected_choice)
    except(Choice.DoesNotExist, KeyError):
        context = {
            'poll_questions': poll_questions,
            'polling_name' : polling_name,
            'error_message':'Проголосуйте во всех вопросах!',
        }
        return render(request, 'appstat/questions.html', context)
    else:       
        context = {
            'poll_questions' : poll_questions,
            'polling_name': polling_name,
            'selected_choice_list' : selected_choice_list,    
        }
        return render(request, 'appstat/results.html', context)

webstatistics/appstat/templates/appstat/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'appstat/style1.css' %}">

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>Polls</title>
  </head>
  <body>
    <h1>  
      <center>
        <p class="name">ОПРОСЫ</p>
      </center>   
    </h1>
    {% if latest_poll_list %}
      {% for poll in latest_poll_list %}
        <center>
            <a href="{% url 'polling:questions' poll.id %}">
              <button class="poll">{{ poll.name }}</button>
            </form>
        </center> 
       </p>
      {% endfor %}
    {% else %}
      <p>Нет доступных опросов.</p>
    {% endif %}
  </h1> 
  </body>
</html>

webstatistics/appstat/templates/appstat/questions.html
{% load static %}
<link rel="stylesheet" href="{% static 'appstat/style2.css' %}">

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Questions</title>
  </head>
  <body>
    <h1>
      <center>
        <p class="name">{{ polling_name }}</p>
        <form action="/polling" method="get">
          <button class="button">К опросам</button>
        </form>
      </center>   
    </h1> 
      <h3>
        {% if error_message %}<center><p class="error-message">{{ error_message }}</center></p>{% endif %}
        <ul>
          <form action="{% url 'polling:results' polling_name.id %}" method="post">
            {% csrf_token %}
            {% for question in poll_questions %}
              <fieldset class="fieldset">
                <legend><h1>{{ question.question_text }}</h1></legend>
                  {% for choice in question.choices.all %}
                    <h2><input type="radio" name="{{ question }}" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br></h2>
                  {% endfor %}
                </fieldset>
              </p>
            {% endfor %}
         </ul>
        <center><input type="submit" class="submit" value="Голосовать"></center>
      </form> 
    </h3> 
  </body>
</html>

webstatistics/appstat/templates/appstat/results.html
{% load static %}
<link rel="stylesheet" href="{% static 'appstat/style3.css' %}">

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Results</title>
  </head>
  <body>
    <h1>
      <center>
        <p class="name">Результаты голсования опроса: "{{ polling_name }}"</p>
        <form action="/polling" method="get">
          <button class="button">К опросам</button>
        </form>
      </center>   
    </h1>
    <ul> 
      {% for ques in poll_questions %} 
        <h1><p class="question">Вопрос: {{ ques.question_text }}</p></h1>
          {% for choice in ques.choices.all %}
            {% if choice in selected_choice_list %}
              <ul><li><p class="selected_choice">{{ choice }}: <span class="votes">{{ choice.votes }}</span></p></li></ul>
            {% else %}
              <ul><li><p class="choice">{{ choice.choice_text }} : {{ choice.votes }}</p></li></ul>
            {% endif %}
          {% endfor %}
        <br>
      {% endfor %}
    </ul>
    <center>
        <form action="{% url 'polling:questions' polling_name.id %}" method="get">
          <button class="button2">Голосовать снова</button>
        </form>
    </center>
  </body>
</html>